### ISSUE TITLE
建议增加AddRaw函数，可以用于浮点数输出精度控制

### ISSUE THREAD

**Issue by zmn0079** [Bwar/CJsonObject#10]
现在这个封装有个问题，无法控制浮点数的输出精度。

新的cjson里面有raw这个类型，可以直接写入原始字符，这样就由开发人员自行控制输出内容，可以解决精度问题。

或者直接增加Add精度参数也行，但是这样就和cjson差别更大了。

**Comment by Bwar** [comment]
> 现在这个封装有个问题，无法控制浮点数的输出精度。
> 
> 新的cjson里面有raw这个类型，可以直接写入原始字符，这样就由开发人员自行控制输出内容，可以解决精度问题。
> 
> 或者直接增加Add精度参数也行，但是这样就和cjson差别更大了。

这个目前不好支持，2018年曾尝试升级cJSON最新版，终因差异太大放弃了。

**Comment by skyformat99** [comment]
还是需要升级到最新版啊
或者转换为字符串输出
