### ISSUE TITLE
请问如何判断某个key是否存在?

### ISSUE THREAD

**Issue by baker-Xie** [Bwar/CJsonObject#18]
使用IsNull似乎不对?

**Comment by Bwar** [comment]
如果明确想知道某个key是否存在，那必然知道这个key的value是什么类型，调用相应的Get()函数，返回true就表明key存在，否则可以不存在。

**Comment by baker-Xie** [comment]
> 如果明确想知道某个key是否存在，那必然知道这个key的value是什么类型，调用相应的Get()函数，返回true就表明key存在，否则可以不存在。

谢谢！今天我似乎也是这么用的。本来以为用IsNull结果发现不对，谢谢。
