### ISSUE TITLE
double 和float好像仍然不兼容不带点的整数，若不带点，理应自动加个.0

### ISSUE THREAD

**Issue by kematy** [Bwar/CJsonObject#2]
double 和float好像仍然不兼容不带点的整数，若不带点，理应自动加个.0,有的程序导出json时可能会把.0去掉，但仍然需要按浮点数读取。

**Comment by Bwar** [comment]
不带小数点的理应为整数而非小数，不补.0是正常的。不过，做一下兼容也并无不可，已经添加了兼容。

**Comment by kematy** [comment]
谢谢，这在读坐标时很有用，因为坐标有整数，也有浮点数，事前不知道类型


 
---原始邮件---
发件人: "Bwar"<notifications@github.com>
发送时间: 2019年7月20日(星期六) 晚上9:02
收件人: "Bwar/CJsonObject"<CJsonObject@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"kematy"<151711064@qq.com>;
主题: Re: [Bwar/CJsonObject] double 和float好像仍然不兼容不带点的整数，若不带点，理应自动加个.0 (#2)



不带小数点的理应为整数而非小数，不补.0是正常的。不过，做一下兼容也并无不可，已经添加了兼容。
