### ISSUE TITLE
prase_number 

### ISSUE THREAD

**Issue by mousexie** [Bwar/CJsonObject#20]
解析这个字串时：1283949231388184576
返回：1283949231388184320

**Comment by Bwar** [comment]
linux下测试过当前最新版本没有这个问题，你的环境和版本是？

**Comment by mousexie** [comment]
windows版本下vs2017编译器，解析出来的数字不一样。如string str = "{\"entrustId\":1331796695786074117}";
返回：1331796695786073856

**Comment by Bwar** [comment]
这是因为parse_number时用了long double来存储，而windows下long double精度不够所致，暂未解决。
