### ISSUE TITLE
建议加入覆盖处理的函数

### ISSUE THREAD

**Issue by YOYOYOYOGA-seu** [Bwar/CJsonObject#24]
使用CJsonObject::Replace()过程中如果出现对应键值项不存在时不会创建，所以在使用过程中如果需要判断Replace是否成功，如果为false则需要自行Add,建议加入：
bool CJsonObject::Override( ... )
{
     if(Replace( ...) == false)
         return Add( ...);
     retrun true;
}
以实现覆盖功能，当没有待替换项时就创建它

**Comment by skyformat99** [comment]
en, 这个不错
