### ISSUE TITLE
建议增加GetKey新的实现方式，或者改名为HasKey

### ISSUE THREAD

**Issue by lkysyzxz** [Bwar/CJsonObject#29]
理由：只想查询是否包含某个Key，而不关心输入的查询字符串被修改。
这样外部调用可以用C风格的字符串。
区别：输入参数加一个const

bool CJsonObject::GetKey(const std::string& strKey)

**Comment by Bwar** [comment]
HasKey是一个无用的函数，如果预期某个key是存在的，那必然知道如果这个key存在，其value是什么类型的，用Get函数在取得value的同时也知道该key是否存在。 如果单纯探测这个key是否存在又不知道其value是什么类型，那判断key是否存在也是毫无意义的操作。

**Comment by lkysyzxz** [comment]
在取得value之前，就知道了key说明json的格式被固定了下来，一定会有的意思。
加探测就可以支持非固定的json格式，因为某个key可能有，也可能没有。有和没有意味着两种不同的操作。

**Comment by Bwar** [comment]
增加了KeyExist()用于检查key是否存在
