### ISSUE TITLE
请问如何用你这个封装的库创建二维数组

### ISSUE THREAD

**Issue by tobetheDuke** [Bwar/CJsonObject#3]
类似“test”:[
[{“test”：1}],
[{“test”：2}]
]

**Comment by Bwar** [comment]
neb::CJsonObject oTest;
oTest.AddEmptySubArray("test");
for (int i = 1; i < 3; ++i)
{
    neb::CJsonObject oDimension1;
    neb::CJsonObject oDimension2;
    oDimension2.Add("test", i);
    oDimension1.Add(oDimension2);
    oTest["test"].Add(oDimension1);
}
std::cout << oTest.ToString() << std::endl;
