### ISSUE TITLE
多线程解析错误json字符串问题——by aiyomajun

### ISSUE THREAD

**Issue by Bwar** [Bwar/CJsonObject#33]
这个封装确实不错，但是我在使用这个库的时候遇到了一些问题:
1.小数点最多只能有6位，位数不能自由控制，这个问题影响不大
2.在多线程中使用会有问题，特别是，多个不同的线程同时Parse 多个非json格式的字符串时，全局的error指针会被另一个线程改写，然后另一个线程快速释放了这部分内存，导致这个指针指向的区域无效，从而发生段错误

**Comment by Bwar** [comment]
@aiyomajun 已修复

**Comment by boyalucky** [comment]
作者您好，这个CJsonObject::Get(int iWhich, double& dValue)只能得到小数点后六位的问题解决了吗？为什么我用这个得到对象的值的时候小数点还是只能六位呀？

**Comment by boyalucky** [comment]
作者您好，这个CJsonObject::Get(int iWhich, double& dValue)只能得到小数点后六位的问题解决了吗？为什么我用这个得到对象的值的时候小数点还是只能六位呀？

**Comment by Bwar** [comment]
v1.5.1可以支持多于6位小数
