### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yuchuanxin** [Bwar/CJsonObject#34]
提示‘cJSON_CreateNumber’ was not declared in this scope
 #define cJSON_AddNumberToObject(object,name,n) cJSON_AddItemToObject(object, name, cJSON_CreateNumber(n))

你这个版本代码里面确实没有cJSON_CreateNumber函数
                                                                                                        ^

**Comment by Bwar** [comment]
CJsonObject中没有用到cJSON_CreateNumber，在写CJsonObject时把cJSON_CreateNumber改成了cJSON_CreateInt和cJSON_CreateDouble，Number是对应json的类型，CJsonObject为了在C++中更方便使用把数据类型与C++中的类型相对应。
使用CJsonObject不建议直接调用cJSON里的函数，更不建议用宏。
