### ISSUE TITLE
大量数据json转换不推荐使用，有严重的性能问题

### ISSUE THREAD

**Issue by elmagnificogi** [Bwar/CJsonObject#35]
数组的动态增加有严重性能问题，直接导致整个函数执行速率下降了30倍左右
两个不同结构的相同数据，以下两种格式会相差30倍效率，前者20秒执行完，后者要10分钟
所有时间都花在了前两个“["Drones"][index]” 对应查询上了
`
相同执行频率，相同数据量，但是只是json格式不同
// 20 秒执行完
Channels_json["Channels"].Add(Channel_json);

// 10分钟执行完
drama_json["Drones"][index]["Channels"].Add(Channel_json);
`

如果这个不优化的话，建议不要使用，大量数据基本撑不住

转换的json数据量大概是200MB左右，如果只是小数据量不明显

**Comment by Bwar** [comment]
谢谢你的建议，之前没在这种场景使用过，会尝试优化。
顺便提一下，CJsonObject说明过为了使用方便牺牲了性能，不适用于数据量大的json是意料之中的事，但还有许多其他场景使用很方便。“不推荐使用，严重的性能问题” 这个issue标题不太适宜。

**Comment by elmagnificogi** [comment]
@Bwar  说的可能还是不完全，总体来说顺序插入大量数据没问题，但是一旦不是顺序插入，性能问题就非常明显了。

前者是在同一个字典中依次插入，后者是几十个字典轮流插入，然后立马就慢的不行

**Comment by elmagnificogi** [comment]
我再更新一下吧
我用rapidjson和你的做同样操作
数据组成按照顺序执行的情况下（中间没有任何插入切换之类的）
rapidjson导出681KB的格式化的可读的json 1s不到吧
CJsonObject导出681KB的格式化的可读的json 120s以上

**Comment by Bwar** [comment]
新版本主要做了两方面优化：
1. Add子json时支持不再做值拷贝不再重新Parse，C++11可以直接调用传递右值引用的Add()函数，C++03则以AddWithMove()替代。
2. operator[]不再每次都直接find，可有效减少连续调用[]对子json操作时调用find的代价。
因数据不好造出来，没有对你200Mjson的场景进行测试过有多大提升，但可以肯定如果用了新版本的右值引用传参或AddWithMove()可以带来较大效率提升。当然，不能跟以效率著称的rapid json相比，CJsonObject主要目标仍然是易用性，在易用性好的前提下才是效率能提升多少就提升多少。
