### ISSUE TITLE
uint64的处理问题

### ISSUE THREAD

**Issue by anyshu** [Bwar/CJsonObject#36]
输入（Add）："userid":4796440449449984
输出（ToString）："userid":1361903616

修改函数：static char *print_int(cJSON *item)中
        sprintf(str, "%lu", item->valueint); **改为** sprintf(str, "%llu", item->valueint);

请检查是否正确？还有2个地方是否需要修改？

Android上使用，MAC编译。
 Thanks!

**Comment by Bwar** [comment]
CJsonObject被用于包括嵌入式平台在内的许多不同平台，对long long的处理方式有差异，我本周加个条件判断走不同的处理分支

**Comment by Bwar** [comment]
已通过预编译宏处理。
