### ISSUE TITLE
parse 64bit integer failed on windows

### ISSUE THREAD

**Issue by lionloveqin** [Bwar/CJsonObject#39]
On Windows platform， use visual studio community 2019 to excute following program，the 1903588763415872642 should be printed，but 1903588763415872512 got.

#include <iostream>
#include "CJsonObject.hpp"

int main()
{
    std::string test_str = "{\"channelQueryId\":1903588763415872642}";
    auto co = neb::CJsonObject(test_str);
    uint64_t id = 0;
    co.Get("channelQueryId", id);
    std::cout << id << std::endl;
    return 0;
}

**Comment by Bwar** [comment]
This is because long double is used for storage in parse_number, and the precision of long double under windows is not enough, it will be fixed on windows later.
