### ISSUE TITLE
部分中文字符Parse()之前是好的，Parse()完之后就乱码了

### ISSUE THREAD

**Issue by pzhu1015** [Bwar/CJsonObject#41]
std::string str= "{\"word_list\":\"胡錦涛\n
胡錦滔\n
胡錦濤\n
胡錦淘\n
胡景涛\"}"
CJsonObject json;
json.Parse(str);
parse完后就有一些问号
word_list="胡逄?胡逄?胡鍧?胡逄?胡景涛"

**Comment by Bwar** [comment]
字符集不是utf8吧？

**Comment by pzhu1015** [comment]
> 字符集不是utf8吧？

VS2015 IDE环境肯定是UTF8的，字符串转换之前都是好的，Parse()后有的字符就变成"?"，并不是所有的中文都会乱，有的中文会乱

**Comment by Bwar** [comment]
我在linux下测试了一下你这个字符串，是OK的，没乱码
