### ISSUE TITLE
直接运行demo出现段错误 (核心已转储)

### ISSUE THREAD

**Issue by wenjing1993** [Bwar/CJsonObject#42]
- 运行至`std::cout << oJson["dynamic_loading"][0]["cmd"][0]("cmd") << std::endl;`
- 使用gdb调试定位到`neb::CJsonObject::operator[] (this=0x558189197c50, uiWhich=0) at ../CJsonObject.cpp:307`

**Comment by Bwar** [comment]
这是个bug，我周末修复一下
可以先用版本[v1.4](https://github.com/Bwar/CJsonObject/tree/v1.4)，这个版本不存在这个问题。
