### ISSUE TITLE
CJsonObject::operator[]   vs2019  c++14  release   have   exception

### ISSUE THREAD

**Issue by omgkaka** [Bwar/CJsonObject#43]
when such code like :
                   std::string=ojson[xxx1][xxx2][xxx3][xxx]\(0\);
it works on debug mode,
but under release mode,evenwith disable optimize,it was crashed;
                maybe the reason is "m_array_iter" uninitialized.

                just modify operator[] function:
		//if (uiWhich == m_uiLastArrayIndex && m_array_iter != m_mapJsonArrayRef.end())
		//{
		//	return(*(m_array_iter->second));
		//}

all things  will be fine.

**Comment by Bwar** [comment]
the bug had been fixed in version v1.5.1
