### ISSUE TITLE
parse_number函数解析double型value时结果不正确

### ISSUE THREAD

**Issue by Elapsed129** [Bwar/CJsonObject#48]
在此函数中如下位置：
        //printf("subscale = %d, signsubscale = %d, s = %.16f\n", subscale, signsubscale, d);
        if (subscale != 0)
        {
            d = item->sign * base * pow(10.0, (scale + subscale * signsubscale)); /* number = +/- number.fraction * 10^+/- exponent */
        }
        item->valuedouble = d;
是不是应该改为：
        if (subscale != 0)
        {
            item->valuedouble = item->sign * base * pow(10.0, (scale + subscale * signsubscale)); /* number = +/- number.fraction * 10^+/- exponent */
        }else
        {
            item->valuedouble = item->sign * d;
        }
        // 在负数double数据时，d没有乘符号，导致负号消失，所以注释掉这句并修改上面的if语句
        // item->valuedouble = d;

**Comment by Bwar** [comment]
这是哪个分支的代码？master里cJSON.c:172已经是像你说的这样的
```c
        if (subscale != 0)
        {
            d = item->sign * base * pow(10.0, (scale + subscale * signsubscale)); /* number = +/- number.fraction * 10^+/- exponent */
        } else {
            d = item->sign * d;
        }
        item->valuedouble = d;
        item->valueint = n;
        item->type = cJSON_Double;
```

**Comment by Elapsed129** [comment]
我记得当时下载的版本是v1.5还是 v1.5.1，如果改过的话我直接拉master的代码好了。
