### ISSUE TITLE
android 编译64位报错

### ISSUE THREAD

**Issue by beasonshu** [Bwar/CJsonObject#49]
darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: CMakeFiles/jniUtil.dir/src/main/jni/CJsonObject.cpp.o: relocation R_AARCH64_MOVW_UABS_G0_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
  CMakeFiles/jniUtil.dir/src/main/jni/CJsonObject.cpp.o: error adding symbols: Bad value
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Bwar** [comment]
应该是你的makefile写得有问题
