### ISSUE TITLE
IsEmpty方法感觉语义不清

### ISSUE THREAD

**Issue by jianjiankedizai** [Bwar/CJsonObject#53]
对于一个没有子节点的CJsonObject，调用这个方法会返回false；
当这个空的CJsonObject调用了Clear之后，再调用IsEmpty又会返回true；
IsEmpty这个方法是用来判断某个节点是空节点的吗？还是用来判断某个节点是否存在的？那么跟IsKeyExist有什么区别呢？

**Comment by Bwar** [comment]
IsEmpty()是用来判断CJsonObject对象是否有内容的（可以理解为是否未初始化，可能用NotInitialized()更合适），与key无关。

**Comment by jianjiankedizai** [comment]
那这个意思是不能用IsEmpty来判断某个CJsonObject是否包含元素

**Comment by code-lgt** [comment]
使用ToString转出来的字符串首尾有\" \"，建议优化
