### ISSUE TITLE
一个下标问题！

### ISSUE THREAD

**Issue by wsz9903011** [Bwar/CJsonObject#54]
{
    "request_id": "4e902ed42eb011edb979179a63eecfae",
    "code": 0,
    "msg": "",
    "data": {
        "fields": [
            "is_open"
        ],
        "items": [
            [
                1
            ]
        ],
        "has_more": false
    }
}
当要获取items 的值时候：
    const char* data = "{\r\n    \"request_id\": \"4e902ed42eb011edb979179a63eecfae\",\r\n    \"code\": 0,\r\n    \"msg\": \"\",\r\n    \"data\": {\r\n        \"fields\": [\r\n            \"is_open\"\r\n        ],\r\n        \"items\": [\r\n            [\r\n                99\r\n            ]\r\n        ],\r\n        \"has_more\": false\r\n    }\r\n}";
    neb::CJsonObject oJson(data);
int  a = 0;
 oJson["data"]["items"][-1] .Get(0, a);  //这样能正常获取a = 1

 oJson["data"]["items"][0] .Get(0, a);  //异常退出  ！！！！！！！

**Comment by Bwar** [comment]
使用最新版本测试你的例子，没发现这个问题

**Comment by wsz9903011** [comment]
release 里面下载的是没问题 , 直接git下来的 好像有问题
