### ISSUE TITLE
json字符串中包含一个value为json格式的字符串用默认构造函数转换失败

### ISSUE THREAD

**Issue by Zero1PP** [Bwar/CJsonObject#55]
char chJsonData[2048] = {0};
  sprintf(chJsonData, g_strAnalysisFormat.c_str(), neb::CJsonObject(stAnalysisInfo.strOutPutList).ToFormattedString().c_str());
neb::CJsonObject itemInfo(chJsonData);

**Comment by Bwar** [comment]
看不懂你这段代码是什么意思

**Comment by Zero1PP** [comment]
例如：	
char chJsonData[2048] = {0};
std::string strJsonData = "[{\"EventID\":1168176694917332992,\"EventName\":\"123\",\"EventType\":2,\
								\"HandleType\":\"%s\"}]";
std::string strJsonData2 = "[{\"EventID\":1168176694917332992,\"EventName\":\"123\",\"EventType\":2,\
								\"HandleType\"}]";
sprintf(chJsonData, strJsonData.c_str(), strJsonData2);
neb::CJsonObject itemInfo(chJsonData);

**Comment by GithubAlanChao** [comment]
> 例如： char chJsonData[2048] = {0}; std::string strJsonData = "[{"EventID":1168176694917332992,"EventName":"123","EventType":2, "HandleType":"%s"}]"; std::string strJsonData2 = "[{"EventID":1168176694917332992,"EventName":"123","EventType":2, "HandleType"}]"; sprintf(chJsonData, strJsonData.c_str(), strJsonData2.c_str()); nebCJsonObjectData) 問題項： 後邊的字符串轉字符串時會出

strJsonData2 的 Json 格式不正確

**Comment by Bwar** [comment]
sprintf(chJsonData, strJsonData.c_str(), strJsonData2.c_str());

**Comment by Zero1PP** [comment]
> 你这个语句生成的都不是json字符串，怎么能不出错

为啥不是呢，后边的json字符串插入在一个“”中，作为字符串使用，假如strJsonData2不是Json格式的字符串的话是能转化成功的。这个我有经过多次测试

**Comment by Bwar** [comment]
你把字符串打印出来看看就知道了，实在不清楚再找个线上json检查工具检查一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月23日(周五) 下午3:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Bwar/CJsonObject] json字符串中包含一个value为json格式的字符串用默认构造函数转换失败 (Issue #55)




  
你这个语句生成的都不是json字符串，怎么能不出错
  
为啥不是呢，后边的json字符串插入在一个“”中，作为字符串使用，假如strJsonData2不是Json格式的字符串的话是能转化成功的。这个我有经过多次测试
