### ISSUE TITLE
请问能否添加对于内存管理的钩子，就像cJSON那样？

### ISSUE THREAD

**Issue by Hao-Lion-ZJU** [Bwar/CJsonObject#61]
我在使用C++开发单片机的时候，寻找到了您轻量级的基于cJSON封装的c++代码。但是在跑实时操作系统（FreeRTOS）的时候会卡死，调试发现我调用RTOS的申请内存接口，但在您代码里面直接用了free导致死机。我修改了您free的部分即可。所以希望可以给用户提供一个钩子，调用不同的内存管理接口。

**Comment by Bwar** [comment]
我没做过单片机代码开发，你可以按你的意思修改然后提交个PR，我合并到版本库里
