### ISSUE TITLE
布尔类型被转化为整数

### ISSUE THREAD

**Issue by AllesUgo** [Bwar/CJsonObject#63]
利用其中的Add方法无法添加布尔类型，会自动变成整数0或者1，或者有其他的办法添加布尔类型？

**Comment by Bwar** [comment]
Add布尔类型需要传递两个bool参数Add(key, true,true)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月9日(周五) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Bwar/CJsonObject] 布尔类型被转化为整数 (Issue #63)




 
利用其中的Add方法无法添加布尔类型，会自动变成整数0或者1，或者有其他的办法添加布尔类型？
