### ISSUE TITLE
cJSON_CreateNumber 没有定义

### ISSUE THREAD

**Issue by tigertall** [Bwar/CJsonObject#65]
cjson.h 中，cJSON_CreateNumber 没有定义，如果使用了 cJSON_AddNumberToObject，无法编译

#define cJSON_AddNumberToObject(object,name,n)	cJSON_AddItemToObject(object, name, cJSON_CreateNumber(n))

**Comment by Bwar** [comment]
CJsonObject 中未使用 cJSON_AddNumberToObject，这个函数应该是在其他版本的cjson中才有

**Comment by tigertall** [comment]
> CJsonObject 中未使用 cJSON_AddNumberToObject，这个函数应该是在其他版本的cjson中才有

是的，然后因为这里有了这个定义，可能会导致不小心使用到，实际上宏展开后就无法编译，能否保持行为一致。同步增加下cJSON_AddNumberToObject 的定义实现，或者删除 cJSON_AddNumberToObject 宏。

**Comment by Bwar** [comment]
OK，这个周末更新一下

**Comment by Bwar** [comment]
已修改
