### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Johnly1986** [Bwar/CJsonObject#8]
1、Replace 接口删除了原有的节点，再新增节点，导致节点迭代时出现野指针（cjson的节点结构是一个链表），希望不要删除而是修改。
2、Add 接口不应该添加同名称键，添加同名键可以报错或者覆盖原有值。
3、GetKey() 一个公有接口获取已有的建保留在内部，其意为何。
希望UP改进。

**Comment by fakerXue** [comment]
建议将Clear和Delete函数修改如下，两个需要同时改，否则析构会出现问题：

void CJsonObject::Clear()
{
	if (!IsArray())
	{
		std::string strKey;
		do
		{
			ResetTraversing(); 
			if (!GetKey(strKey))
				break;
			Delete(strKey);
		} while (true);
	}
	else
	{
		while (GetArraySize()>0)Delete(0);
	}
}


bool CJsonObject::Delete(const std::string& strKey)
{
    cJSON* pFocusData = NULL;
    if (m_pJsonData == NULL)
    {
        pFocusData = m_pExternJsonDataRef;
    }
    else
    {
        pFocusData = m_pJsonData;
    }
    if (pFocusData == NULL)
    {
        m_strErrMsg = "json data is null!";
        return(false);
    }
    if (pFocusData->type != cJSON_Object)
    {
        m_strErrMsg = "not a json object! json array?";
        return(false);
    }
    std::map<std::string, JsonUtil*>::iterator iter = m_mapJsonObjectRef.find(strKey);
    if (iter != m_mapJsonObjectRef.end())
    {
        if (iter->second != NULL)
        {
            delete (iter->second);
            iter->second = NULL;
        }
        m_mapJsonObjectRef.erase(iter);
	}
	cJSON_DeleteItemFromObject(pFocusData, strKey.c_str()); // 移到此处
    m_listKeys.clear();
    return(true);
}

**Comment by Bwar** [comment]
这个所谓的野指针是CJsonObject的私有成员变量，外部完全不会访问到，这样的野指针其实无伤大雅。不过，按建议改一下确实挺好。Bwar近期正忙于[Nebula](https://github.com/Bwar/Nebula)的一个大版本，暂无时间优化，如果两位有兴趣，欢迎提交PR。

**Comment by zhanb** [comment]
要是有一个CJsonObject 和其他CJson,jsoncpp这些其他json库的性能分析就好了

**Comment by Bwar** [comment]
> 要是有一个CJsonObject 和其他CJson,jsoncpp这些其他json库的性能分析就好了

可以参考 [nativejson-benchmark](https://github.com/miloyip/nativejson-benchmark)， CJsonObject是对cJSON的封装，性能会略低于cJSON。

**Comment by zhanb** [comment]
多谢回复。是不是可以加上一个判断是否为标准json格式的字符串的接口

**Comment by Bwar** [comment]
> 1、Replace 接口删除了原有的节点，再新增节点，导致节点迭代时出现野指针（cjson的节点结构是一个链表），希望不要删除而是修改。
> 2、Add 接口不应该添加同名称键，添加同名键可以报错或者覆盖原有值。
> 3、GetKey() 一个公有接口获取已有的建保留在内部，其意为何。
> 希望UP改进。

已对 2、3 进行优化，1是cJSON里的实现，并不是CJsonObject这么做的。其实修改不一定能做到的，replace之后的value可能超过原value的内存空间，这种情况下必须重新分配空间才能replace成功。

**Comment by Bwar** [comment]
> 建议将Clear和Delete函数修改如下，两个需要同时改，否则析构会出现问题：
> 
> void CJsonObject::Clear()
> {
> if (!IsArray())
> {
> std::string strKey;
> do
> {
> ResetTraversing();
> if (!GetKey(strKey))
> break;
> Delete(strKey);
> } while (true);
> }
> else
> {
> while (GetArraySize()>0)Delete(0);
> }
> }
> 
> bool CJsonObject::Delete(const std::string& strKey)
> {
> cJSON* pFocusData = NULL;
> if (m_pJsonData == NULL)
> {
> pFocusData = m_pExternJsonDataRef;
> }
> else
> {
> pFocusData = m_pJsonData;
> }
> if (pFocusData == NULL)
> {
> m_strErrMsg = "json data is null!";
> return(false);
> }
> if (pFocusData->type != cJSON_Object)
> {
> m_strErrMsg = "not a json object! json array?";
> return(false);
> }
> std::map<std::string, JsonUtil*>::iterator iter = m_mapJsonObjectRef.find(strKey);
> if (iter != m_mapJsonObjectRef.end())
> {
> if (iter->second != NULL)
> {
> delete (iter->second);
> iter->second = NULL;
> }
> m_mapJsonObjectRef.erase(iter);
> }
> cJSON_DeleteItemFromObject(pFocusData, strKey.c_str()); // 移到此处
> m_listKeys.clear();
> return(true);
> }

这样改的理由是什么，只为了保持m_pJsonData指针地址不变？
